license = "BSD3"
with_readme = true

[files]
directories = ["src", "web-src", "mad-src"]
templates = ["src/Main.hs", "shake.hs", "{{ project }}.cabal", "Justfile", "mad-src/{{ project }}.mad", "web-src/styles.css", "web-src/index.html", "stack.yaml", "cabal.project.local"]

[config]
version = "0.1.0.0"
version_control = "git"
